version: "3.7"

services:
  server:
    image: docker.io/unbabel/replicant:latest
    ports:
      - "8080:8080"
    volumes:
      - data:/data
    configs:
      - config.yaml
    command: /app/replicant -config /config.yaml
  cdp:
    image: docker.io/unbabel/replicant:replicant-cdp-latest
    deploy:
      mode: replicated
      replicas: 2
volumes:
  data: null
configs:
  config.yaml:
    file: ./example-config.yaml

